line-length = 100
target-version = "py310"

# Rule sets: E/F/W (pycodestyle/pyflakes), I (isort), UP (pyupgrade),
# N (pep8-naming), B (bugbear), C4 (comprehensions)
lint.select = ["E", "F", "W", "I", "UP", "N", "B", "C4"]

# Black handles these:
lint.ignore = [
  "E203",
  "E501",
]

[lint.per-file-ignores]
# example: allow 'assert' in tests if you want later
"tests/**/*" = []
